import aLogo from "../../public/mainlogo.png";
import logo1 from "../../public/logos/1.jpg";
import logo2 from "../../public/logos/2.jpg";
import logo3 from "../../public/logos/3.jpg";
import logo4 from "../../public/logos/4.jpg";
import logo5 from "../../public/logos/5.jpg";
import logo6 from "../../public/logos/6.jpg";
import logo7 from "../../public/logos/7.jpg";
import logo8 from "../../public/logos/8.jpg";
import logo9 from "../../public/logos/9.jpg";
import logo10 from "../../public/logos/10.jpg";
import logo11 from "../../public/logos/11.jpg";
import logo12 from "../../public/logos/12.jpg";
import logo13 from "../../public/logos/13.jpg";
import logo14 from "../../public/logos/14.jpg";
import logo15 from "../../public/logos/15.jpg";

export const mainLogo = aLogo;
export const Logo1 = logo1;
export const Logo2 = logo2;
export const Logo3 = logo3;
export const Logo4 = logo4;
export const Logo5 = logo5;
export const Logo6 = logo6;
export const Logo7 = logo7;
export const Logo8 = logo8;
export const Logo9 = logo9;
export const Logo10 = logo10;
export const Logo11 = logo11;
export const Logo12 = logo12;
export const Logo13 = logo13;
export const Logo14 = logo14;
export const Logo15 = logo15;

import poster1 from "../../public/posters/1.jpg";
import poster2 from "../../public/posters/2.jpg";
import poster3 from "../../public/posters/3.jpg";
import poster4 from "../../public/posters/4.jpg";
import poster5 from "../../public/posters/5.jpg";
import poster6 from "../../public/posters/6.jpg";
import poster7 from "../../public/posters/7.jpg";
import poster8 from "../../public/posters/8.jpg";
import poster9 from "../../public/posters/9.jpg";

export const Poster1 = poster1;
export const Poster2 = poster2;
export const Poster3 = poster3;
export const Poster4 = poster4;
export const Poster5 = poster5;
export const Poster6 = poster6;
export const Poster7 = poster7;
export const Poster8 = poster8;
export const Poster9 = poster9;

import post1 from "../../public/posts/1.jpg";
import post2 from "../../public/posts/2.jpg";
import post3 from "../../public/posts/3.jpg";
import post4 from "../../public/posts/4.jpg";
import post5 from "../../public/posts/5.jpg";
import post6 from "../../public/posts/6.jpg";
import post7 from "../../public/posts/7.jpg";
import post8 from "../../public/posts/8.jpg";
import post9 from "../../public/posts/9.jpg";
import post10 from "../../public/posts/10.jpg";
import post11 from "../../public/posts/11.jpg";
import post12 from "../../public/posts/12.jpg";
import post13 from "../../public/posts/13.jpg";
import post14 from "../../public/posts/14.jpg";
import post15 from "../../public/posts/15.jpg";
import post16 from "../../public/posts/16.jpg";
import post17 from "../../public/posts/17.jpg";
import post18 from "../../public/posts/18.jpg";
import post19 from "../../public/posts/19.jpg";
import post20 from "../../public/posts/20.jpg";
import post21 from "../../public/posts/21.jpg";
import post22 from "../../public/posts/22.jpg";
import post23 from "../../public/posts/23.jpg";
import post24 from "../../public/posts/24.jpg";
import post25 from "../../public/posts/25.jpg";
import post26 from "../../public/posts/26.jpg";

export const Post1 = post1;
export const Post2 = post2;
export const Post3 = post3;
export const Post4 = post4;
export const Post5 = post5;
export const Post6 = post6;
export const Post7 = post7;
export const Post8 = post8;
export const Post9 = post9;
export const Post10 = post10;
export const Post11 = post11;
export const Post12 = post12;
export const Post13 = post13;
export const Post14 = post14;
export const Post15 = post15;
export const Post16 = post16;
export const Post17 = post17;
export const Post18 = post18;
export const Post19 = post19;
export const Post20 = post20;
export const Post21 = post21;
export const Post22 = post22;
export const Post23 = post23;
export const Post24 = post24;
export const Post25 = post25;
export const Post26 = post26;
